SHOW DATABASES;

DROP DATABASE IF EXISTS example;
DROP DATABASE IF EXISTS sample;

CREATE DATABASE example;

USE example;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INT UNSIGNED NOT NULL UNIQUE,
    name VARCHAR(255));
    
DESC users;